#include <lv2/macros.h.S>
#include <lv2/symbols.h>

LV2_FUNCTION(cellUsbdRegisterLdd, cellUsbdRegisterLdd_symbol)
LV2_FUNCTION(cellUsbdUnregisterLdd, cellUsbdUnregisterLdd_symbol)
LV2_FUNCTION(cellUsbdScanStaticDescriptor, cellUsbdScanStaticDescriptor_symbol)
LV2_FUNCTION(cellUsbdOpenPipe, cellUsbdOpenPipe_symbol)
LV2_FUNCTION(cellUsbdClosePipe, cellUsbdClosePipe_symbol)
LV2_FUNCTION(cellUsbdControlTransfer, cellUsbdControlTransfer_symbol)
LV2_FUNCTION(cellUsbdBulkTransfer, cellUsbdBulkTransfer_symbol)


