
clean:
	rm -f *.o *.elf *.self *.484 *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

all:
	rm -f *.o *.elf *.self *.482 *.bin *.482C *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	make -f Makefile_482C --no-print-directory

	rm -f *.o *.elf *.self *.484 *.bin *.484C *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	make -f Makefile_484C --no-print-directory

	rm -f *.o *.elf *.self *.485 *.bin *.485 *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	make -f Makefile_485C --no-print-directory

	rm -f *.o *.elf *.self *.484 *.bin *.484D *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	make -f Makefile_484D --no-print-directory    
	rm -f *.o *.bin *.elf *.484 *.484d *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	#rm -f *.o *.elf *.self ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
