
clean:
	rm -f *.o *.elf *.self *.484 *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	rm -f *.o *.elf *.self *.485 *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	rm -f *.o *.elf *.self *.486 *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	rm -f *.o *.elf *.self *.487 *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	rm -f *.o *.elf *.self *.488 *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	rm -f *.o *.elf *.self *.489 *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	rm -f *.o *.elf *.self *.490 *.bin *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

all:
	rm -f *.o *.elf *.self *.484 *.bin *.484D *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	make -f Makefile_484D --no-print-directory    
	rm -f *.o *.bin *.elf *.484 *.484d *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	
	rm -f *.o *.elf *.self *.484 *.bin *.484C *.484D *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	make -f Makefile_484C --no-print-directory
	rm -f *.o *.bin *.elf *.484 *.484 *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

	rm -f *.o *.elf *.self *.485 *.bin *.485 *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	make -f Makefile_485C --no-print-directory 
	rm -f *.o *.bin *.elf *.485 *.485 *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

	rm -f *.o *.elf *.self *.486 *.bin *.486 *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	make -f Makefile_486C --no-print-directory 
	rm -f *.o *.bin *.elf *.486 *.486 *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

	rm -f *.o *.elf *.self *.487 *.bin *.487 *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	make -f Makefile_487C --no-print-directory 
	rm -f *.o *.bin *.elf *.487 *.487 *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

	rm -f *.o *.elf *.self *.488 *.bin *.488 *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	make -f Makefile_488C --no-print-directory 
	rm -f *.o *.bin *.elf *.488 *.488 *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

	rm -f *.o *.elf *.self *.489 *.bin *.489 *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	make -f Makefile_489C --no-print-directory 
	rm -f *.o *.bin *.elf *.489 *.489 *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o

	rm -f *.o *.elf *.self *.490 *.bin *.490 *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
	make -f Makefile_490C --no-print-directory 
	rm -f *.o *.bin *.elf *.490 *.490 *.map ../lv1/src/*.o ../debug/src/*.o ../lv2/src/*.o
